### ISSUE TITLE
Unable to set Name on Guest Dealer Badge

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/mff-rams-plugin#110]
1. Start w/ #109 
1. From the badge's admin page, click on "this attendee must register themself" link
1. Name fields are disabled on attendee-facing reg page.
<img width="1053" alt="screen shot 2018-08-18 at 13 42 44" src="https://user-images.githubusercontent.com/910490/44302445-464a7100-a2ee-11e8-832a-9a68e67913b8.png">

**Comment by jmdawson** [comment]
Maybe we can sort this in Iteration 4. I'd like it, though it's probably not biting us too badly right now.

**Comment by kitsuta** [comment]
The name fields on this page are uneditable because otherwise anyone could just change the name the badge is under, effectively 'transferring' it.

There's two ways to handle this use case:
1. Check the Placeholder tick box (the one that says "This attendee needs to register themself" and save the attendee. Placeholder attendees may edit their name while confirming their badge. However, this seems to behave a little oddly for unassigned badges, so I recommend the other method.
2. Use the "Link for group leader" on the group page, then the "Register someone for this badge" link on the next page. This is the form that unassigned group members are intended to fill out.

**Comment by jmdawson** [comment]
I copied this explanation into the wiki so that we don't lose it going forward. I'm not sure if there's a better place to document it, especially from a broader perspective of how RAMS is expected to work.
