### ISSUE TITLE
Remove all mention of refunds from RAMS

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/mff-rams-plugin#69]
Now that we've removed badge refunds, we need to purge all the references. Here's a quick start:
From `quickstart/src`:

`grep -ir "refund" ./ | egrep "(template|static)" > ~/tmp/rams-refunds.txt`

```
.//badge_printing/badge_printing/templates/kiosk_printing/reprint_fee.html:        <button class="btn btn-success" type="submit" name="refund" value="True">Refund Reprint Fee</button>
.//mff-rams-plugin/mff_rams_plugin/templates/preregistration/disclaimers.html:<li><span style="font-weight:bold ; color:red">Purchased registration are non-refundable.</span> Please <a href="mailto:registration@furfest.org">contact registration</a> for other options before the close of preregistration on {{c.PREREG_TAKEDOWN|datetime_local}}.</li>
.//mff-rams-plugin/mff_rams_plugin/templates/preregistration/disclaimers.html:<li> Midwest Furfest has a one badge per person policy. If you purchase multiple badges (for your family, friend, or as a gift), please ensure that each badge is purchased in the name of the individual who the badge is intended for. You may use the same email address for multiple badges so any surprises aren't ruined. The purchaser retains sole ownership of the badge until the end of preregistration and may request a refund of a purchased badge.</li>
.//mff-rams-plugin/mff_rams_plugin/templates/preregistration/disclaimers.html:    <li> Table costs and memberships may be refunded if you need to cancel your dealership. Tables may not be transferred under any circumstances.</li>
.//mff-rams-plugin/mff_rams_plugin/templates/static_views/dealerRules.html:<li>If for any reason you are unable to deal at Midwest FurFest, please notify us promptly. Full refunds can be made if we receive your cancellation prior to {{ c.DEALER_REG_SHUTDOWN|datetime_local }}. After that date, refunds are possible only if we are able to resell your space.
.//mff-rams-plugin/mff_rams_plugin/templates/static_views/stafferComps.html:  <li> For {{c.HOURS_FOR_REFUND}}  hours of logged service, you will receive a free membership to next year's {{c.EVENT_NAME}} and special “Thank You” medal
.//uber/uber/templates/emails/mivs/2018_email_blast.txt:2) Badge refunds
.//uber/uber/templates/emails/mivs/2018_email_blast.txt:2) Badge refunds
.//uber/uber/templates/emails/mivs/2018_email_blast.txt:As being part of MIVS, you're given two free badges to MAGFest.  If you already paid for a badge, we're now ready to handle refunds.  Please email mivs@magfest.org with your refund request.  
.//uber/uber/templates/emails/mivs/judge_badge_info.txt:{% if judge.attendee.paid == c.NEED_NOT_PAY %}Your complementary badge will be waiting for you at our registration desk under your name ({{ judge.attendee.full_name }}).  Simply bring a photo ID to pick it up.{% else %}We provide complementary badges to our judges, but if you already paid for a badge, please reply to this email to let us know to issue you a refund.  Due to limitations in our system, we can not transfer badges to other people right now.{% endif %}
.//uber/uber/templates/emails/panels/panel_app_accepted.txt:Important: If you or any others on your panel have purchased badges, {{ c.EVENT_NAME }} will refund the purchase price.  Please let us know if this is the case so we can get your refund sooner. As a reminder {{ c.EVENT_NAME }} will be held {{ c.EPOCH|datetime_local("%A, %B %-d") }} through {{ c.ESCHATON|datetime_local("%A, %B %-d") }} at {{ c.EVENT_VENUE }}.
.//uber/uber/templates/emails/reg_workflow/attendee_confirmation.html:    {{ c.EVENT_NAME }} has a no-refund policy for all registrations.  If for any reason you can't make it, we allow and encourage
.//uber/uber/templates/emails/reg_workflow/attendee_qrcode.html:    {{ c.EVENT_NAME }} has a no-refund policy for all registrations.  If for any
.//uber/uber/templates/emails/reg_workflow/payment_refunded.txt:Your {{ c.EVENT_NAME_AND_YEAR }} registration has been refunded in the amount of ${{ attendee.amount_refunded }}.  Unless you've already been told otherwise in a person, this amount will be refunded to the credit card used to pay for the registration.  You can expect the money to show up in 5-10 business days.
.//uber/uber/templates/groups/form.html:    <label class="col-sm-3 control-label">Amount Refunded</label>
.//uber/uber/templates/groups/form.html:        $<input type="text" style="width:4em" name="amount_refunded" value="{{ group.amount_refunded }}" />
.//uber/uber/templates/mivs_admin/judges_owed_refunds.html:{% block title %}Judges Owed Refunds{% endblock %}
.//uber/uber/templates/mivs_admin/judges_owed_refunds.html:<h2>Judges Owed Refunds</h2>
.//uber/uber/templates/mivs_admin/judges_owed_refunds.html:  have paid and not been refunded:
.//uber/uber/templates/preregistration/disclaimers.html:    Your registration is <a href="http://super.magfest.org/faq#-KAbbdlWaUSQd_sAxmw2">non-refundable</a>
.//uber/uber/templates/preregistration/repurchase.html:    <h2>Refunded Badge</h2>
.//uber/uber/templates/preregistration/repurchase.html:    According to our records, your badge has been refunded. You may repurchase your badge at the current price of
.//uber/uber/templates/registration/form.html:        setVisible('#amount_refunded', paid === {{ c.REFUNDED }});
.//uber/uber/templates/registration/form.html:        <span id="amount_refunded">
.//uber/uber/templates/registration/form.html:            Refunded: $<input type="text" style="width:4em" name="amount_refunded" value="{{ attendee.amount_refunded }}" />
.//uber/uber/templates/schedule/panelists_owed_refunds.html:{% block title %}Panelists Owed Refunds{% endblock %}
.//uber/uber/templates/schedule/panelists_owed_refunds.html:<h2>Panelists Owed Refunds</h2>
.//uber/uber/templates/schedule/panelists_owed_refunds.html:and not been refunded:
.//uber/uber/templates/signups/printable_schedule.html:        get your badge refund, plus you won't
.//uber/uber/templates/static_views/dealerRules.html:    <li> No refunds are provided at anytime should you decide to leave {{ c.EVENT_NAME }} and stop selling before the event is over. We reserved your space on a per-event basis, not a per-day basis, so even partial refunds are not possible. </li>
.//uber/uber/templates/static_views/groups.html:No refunds will be given for unused badges, but badges may be transferred to other
.//uber/uber/templates/static_views/howToStaff.html:Volunteers are rewarded with tshirts, badge refunds, and more!  <a href="stafferComps.html">Click here</a> to
.//uber/uber/templates/static_views/stafferComps.html:    <li> Working at least {{ c.HOURS_FOR_REFUND }} hours gets you a refund on your badge for this year. <br/><br/> </li>
.//uber/uber/templates/summary/volunteers_owed_refunds.html:{% block title %}Volunteers Owed Refunds{% endblock %}

```

**Comment by ianlayton** [comment]
Just as a note, we *should* allow registration to flag registration as refunded, because there may be edge cases where we need to allow this. What we need to do is make sure that the option isn't shown as an option to people registering.

Really, we don't need to change code more then just make sure that we remove any mention of doing it in text displayed to people registering.

**Comment by kitsuta** [comment]
`.//badge_printing/badge_printing/templates/kiosk_printing/reprint_fee.html`
Admin function; shouldn't need changing as per Ian's comment.

`.//mff-rams-plugin/mff_rams_plugin/templates/preregistration/disclaimers.html`
Covered by https://github.com/MidwestFurryFandom/mff-rams-plugin/issues/68 (the reason is appears twice is that one bullet point says badges are 'non-refundable')

`.//mff-rams-plugin/mff_rams_plugin/templates/preregistration/disclaimers.html:    <li> Table costs and memberships may be refunded if you need to cancel your dealership. Tables may not be transferred under any circumstances.</li>`
**Attendee-facing, remove or replace**

`.//mff-rams-plugin/mff_rams_plugin/templates/static_views/dealerRules.html:<li>If for any reason you are unable to deal at Midwest FurFest, please notify us promptly. Full refunds can be made if we receive your cancellation prior to {{ c.DEALER_REG_SHUTDOWN|datetime_local }}. After that date, refunds are possible only if we are able to resell your space.`
**Attendee-facing, remove or replace**

`.//mff-rams-plugin/mff_rams_plugin/templates/static_views/stafferComps.html:  <li> For {{c.HOURS_FOR_REFUND}}  hours of logged service, you will receive a free membership to next year's {{c.EVENT_NAME}} and special “Thank You” medal`
**Attendee-facing**, but volunteers still probably get refunds?

`.//uber/uber/templates/emails/mivs/2018_email_blast.txt`
`.//uber/uber/templates/emails/mivs/judge_badge_info.txt`
This plugin is turned off because MFF does not have an indie videogame showcase (...go figure).

`.//uber/uber/templates/emails/panels/panel_app_accepted.txt:Important: If you or any others on your panel have purchased badges, {{ c.EVENT_NAME }} will refund the purchase price.  Please let us know if this is the case so we can get your refund sooner. As a reminder {{ c.EVENT_NAME }} will be held {{ c.EPOCH|datetime_local("%A, %B %-d") }} through {{ c.ESCHATON|datetime_local("%A, %B %-d") }} at {{ c.EVENT_VENUE }}.`
**Attendee-facing**, but won't be visible unless MFF starts using the panels plugin. If they do, should compare this to panel badges policies.

`.//uber/uber/templates/emails/reg_workflow/attendee_confirmation.html`
`.//uber/uber/templates/emails/reg_workflow/attendee_qrcode.html`
These both say 'no-refund policy'.

`.//uber/uber/templates/emails/reg_workflow/payment_refunded.txt`
This is an email that goes to people when you mark them as refunded. Probably worth checking into.

`.//uber/uber/templates/groups/form.html`
Admin area.

`.//uber/uber/templates/mivs_admin/judges_owed_refunds.html
.//uber/uber/templates/mivs_admin/judges_owed_refunds.html
.//uber/uber/templates/mivs_admin/judges_owed_refunds.html`
Admin area, plus MIVS is unused as per earlier comment.

`.//uber/uber/templates/preregistration/disclaimers.html:`
It says registrations are 'non-refundable'

`.//uber/uber/templates/preregistration/repurchase.html`
This page is for self-service re-registering after a badge has been refunded. Worth checking to make sure MFF still wants this option presented to attendees when they're marked Refunded.

`.//uber/uber/templates/registration/form.html`
`.//uber/uber/templates/schedule/panelists_owed_refunds.html`
Admin area.

`.//uber/uber/templates/signups/printable_schedule.html:        get your badge refund, plus you won't`
**Attendee-facing**, looks like it's related to our volunteer signup process.

`.//uber/uber/templates/static_views/dealerRules.html`
"No refunds are provided at any time"

`.//uber/uber/templates/static_views/groups.html`
Attendee group explanation, and it says badges are non-refundable anyway.

`.//uber/uber/templates/static_views/howToStaff.html:Volunteers are rewarded with tshirts, badge refunds, and more!  <a href="stafferComps.html">Click here</a> to`
.//uber/uber/templates/static_views/stafferComps.html:    <li> Working at least {{ c.HOURS_FOR_REFUND }} hours gets you a refund on your badge for this year. <br/><br/> </li>`
**Attendee-facing**, related to volunteer compensation.

`.//uber/uber/templates/summary/volunteers_owed_refunds.html`
Admin area.

As a side note/reminder:
The payment option "paid and refunded" should be set for any badge that is partially or fully refunded for any reason, including comped badges.
"Refunded," the badge status, renders the badge unable to check in. It should only be used for attendees who were refunded because they are not coming to the event.

**Comment by ianlayton** [comment]
Please cancel this request. After some deliberation, we've decided to allow refunds again.
